"""description_of_migration

Revision ID: 0f092bcc2551
Revises: 
Create Date: 2024-02-14 12:08:55.795001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f092bcc2551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_plant_diseases_id', table_name='plant_diseases')
    op.drop_index('ix_plant_diseases_plant_disease_description', table_name='plant_diseases')
    op.drop_index('ix_plant_diseases_plant_disease_name', table_name='plant_diseases')
    op.drop_index('ix_plant_diseases_plant_disease_recommendation', table_name='plant_diseases')
    op.drop_table('plant_diseases')
    op.drop_index('ix_plant_types_id', table_name='plant_types')
    op.drop_index('ix_plant_types_plant_type_name', table_name='plant_types')
    op.drop_table('plant_types')
    op.drop_index('ix_user_histories_id', table_name='user_histories')
    op.drop_table('user_histories')
    op.drop_index('ix_recommendations_disease_name', table_name='recommendations')
    op.drop_index('ix_recommendations_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_plants_id', table_name='plants')
    op.drop_index('ix_plants_image_path', table_name='plants')
    op.drop_index('ix_plants_plant_description', table_name='plants')
    op.drop_index('ix_plants_plant_name', table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('plant_name', sa.VARCHAR(), nullable=False),
    sa.Column('plant_description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plants_plant_name', 'plants', ['plant_name'], unique=1)
    op.create_index('ix_plants_plant_description', 'plants', ['plant_description'], unique=False)
    op.create_index('ix_plants_image_path', 'plants', ['image_path'], unique=False)
    op.create_index('ix_plants_id', 'plants', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('disease_name', sa.VARCHAR(), nullable=True),
    sa.Column('preventive_measure', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_id', 'recommendations', ['id'], unique=False)
    op.create_index('ix_recommendations_disease_name', 'recommendations', ['disease_name'], unique=1)
    op.create_table('user_histories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('prediction', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('preventive_measure', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_histories_id', 'user_histories', ['id'], unique=False)
    op.create_table('plant_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('plant_type_name', sa.VARCHAR(), nullable=False),
    sa.Column('plant_type_description', sa.VARCHAR(), nullable=True),
    sa.Column('plant_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plant_types_plant_type_name', 'plant_types', ['plant_type_name'], unique=1)
    op.create_index('ix_plant_types_id', 'plant_types', ['id'], unique=False)
    op.create_table('plant_diseases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('plant_disease_name', sa.VARCHAR(), nullable=False),
    sa.Column('plant_disease_description', sa.VARCHAR(), nullable=True),
    sa.Column('plant_disease_recommendation', sa.VARCHAR(), nullable=True),
    sa.Column('plant_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plant_diseases_plant_disease_recommendation', 'plant_diseases', ['plant_disease_recommendation'], unique=False)
    op.create_index('ix_plant_diseases_plant_disease_name', 'plant_diseases', ['plant_disease_name'], unique=1)
    op.create_index('ix_plant_diseases_plant_disease_description', 'plant_diseases', ['plant_disease_description'], unique=False)
    op.create_index('ix_plant_diseases_id', 'plant_diseases', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
